databases:
  - name: appdb
    databaseName: appdb

services:
  - type: web
    name: veterans-benefits-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: TEST_FLAG
        value: on
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: veterans-benefits-kb