services:
  - type: web
    name: rag-flask-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY  
        sync: false
      - key: PINECONE_INDEX
        value: veteran-rag
      - key: PINECONE_NAMESPACE
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MODEL_BIG
        value: gpt-4o
      - key: MODEL_SMALL
        value: gpt-4o-mini
      - key: EMBED_MODEL
        value: text-embedding-3-small
      - key: RETRIEVAL_TOP_K
        value: 50
      - key: RERANK_TOP_K
        value: 8
      - key: COMPRESS_BUDGET_TOKENS
        value: 2200
      - key: WORKERS
        value: 2
      - key: THREADS
        value: 4