services:
  - type: web
    name: veteran-ai-spark-frontend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l 10000
    envVars:
      - key: NODE_VERSION
        value: 18.17.0