services:
  - type: static_site
    name: VBai-subdir
    buildCommand: npm ci --prefix veteran-ai-spark && npm run build --prefix veteran-ai-spark
    publishPath: veteran-ai-spark/dist
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
services:
  - type: web
    name: my-node-app
    env: node
    plan: starter
    region: oregon
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"